apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-argocd-api
  name: sample-argocd-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-argocd-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-argocd-api
    spec:
      containers:
      - image: vyashemang/sample-argocd-api:40
        name: sample-argocd-api
