version: v1
kind: Deployment
metadata:
  name: sample-argocd-api
  namespace: sample-argocd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-argocd-api
  template:
    metadata:
      labels:
        app: sample-argocd-api
      spec:
        containers:
          - name: sample-argocd-api
            image: vyashemang/sample-argocd-api:33
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
